services:
  proxy:
    container_name: proxy
    image: 'jc21/nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_ROOT}/proxy-manager/data:/data
      - ${CONFIG_ROOT}/proxy-manager/letsencrypt:/etc/letsencrypt
    links:
      - sonarr
      - radarr
      - lidarr
      - static
      - readarr
      - jellyfin
      - prowlarr
      - calibre-web
      - calibre
      - qbittorrent

  static:
    container_name: static-host
    build:
      context: ./static
    restart: always
    volumes:
      - ${STATIC_ROOT}:/home/static
    ports:
      - 3000:3000
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=7081
      - TORRENTING_PORT=6881
    volumes:
      - /${CONFIG_ROOT}/qbittorrent:/config
      - ${MEDIA_ROOT}:/media
    ports:
      - 7081:7081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - 9696:9696
    restart: always

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/sonarr:/config # config files
      - ${MEDIA_ROOT}:/media
    links:
      - qbittorrent
  
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr
    restart: always
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/lidarr:/config # config files
      - ${MEDIA_ROOT}:/media
    links:
      - qbittorrent

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: always
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/radarr:/config # config files
      - ${MEDIA_ROOT}:/media
    links:
      - qbittorrent
  
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG_ROOT}/readarr:/config
      - ${MEDIA_ROOT}:/media
    ports:
      - 8787:8787
    links:
      - qbittorrent
    restart: unless-stopped
  
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${CONFIG_ROOT}/calibre-web:/config
      - ${MEDIA_ROOT}:/media
    ports:
      - 8083:8083
    restart: unless-stopped
  
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - SUBFOLDER=/calibre/
      - NO_FULL
    volumes:
      - ${CONFIG_ROOT}/calibre:/config
      - ${MEDIA_ROOT}:/media
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG_ROOT}/jellyfin:/config
      - ${MEDIA_ROOT}/TV Shows:/data/tvshows
      - ${MEDIA_ROOT}/Movies:/data/movies
      - ${MEDIA_ROOT}/Music:/data/music
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    deploy:
      resources:
        limits:
          memory: 2.5G
    restart: unless-stopped
