version: "3"
services:
  proxy:
    container_name: proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_ROOT}/proxy-manager/data:/data
      - ${CONFIG_ROOT}/proxy-manager/letsencrypt:/etc/letsencrypt
    links:
      - sonarr
      - radarr
      - lidarr
      - jackett
      - deluge
      - static
  
  static:
    container_name: static-host
    build:
      context: ./static
    restart: always
    volumes:
      - ${STATIC_ROOT}:/home/static
    ports:
      - 3000:3000

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge
    restart: always
    ports:
      - 8112:8112
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DELUGE_LOGLEVEL=info
    volumes:
      - ${MEDIA_ROOT}/Downloads:/media/Downloads # downloads folder
      - ${CONFIG_ROOT}/deluge:/config # config files

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett
    restart: always
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_ROOT}/Downloads/torrent-blackhole:/media/Downloads/torrent-blackhole # place where to put .torrent files for manual download
      - ${CONFIG_ROOT}/jackett:/config # config files

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/sonarr:/config # config files
      - ${MEDIA_ROOT}:/media
  
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr
    restart: always
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/lidarr:/config # config files
      - ${MEDIA_ROOT}:/media

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr
    restart: always
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_ROOT}/radarr:/config # config files
      - ${MEDIA_ROOT}:/media

