include:
  - streaming/docker-compose.yml
  - network/docker-compose.yml

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 3 * * *" --disable-containers static-host --cleanup

  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_ROOT}/traefik/acme.json:/acme.json
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.nas.iammikhail.com`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.dashboard.service=api@internal"
    networks:
      - default
      - proxy_net

  static:
    container_name: static-host
    build:
      context: ./static
    restart: always
    volumes:
      - ${STATIC_ROOT}:/home/static
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`downloads.iammikhail.com`)"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=cloudflare"
      - "traefik.http.services.static.loadbalancer.server.port=3000"
    networks:
      - default
      - proxy_net

networks:
  default:
    driver: bridge
  proxy_net:
    external: true
