include:
  - streaming/docker-compose.yml
  - network/docker-compose.yml

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 3 * * *" --disable-containers static-host --cleanup

  proxy:
    container_name: proxy
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_ROOT}/proxy-manager/data:/data
      - ${CONFIG_ROOT}/proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - default
      - proxy_net

  static:
    container_name: static-host
    build:
      context: ./static
    restart: always
    volumes:
      - ${STATIC_ROOT}:/home/static
    ports:
      - 3000:3000

networks:
  default:
    driver: bridge
  proxy_net:
    external: true
