services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    restart: unless-stopped
    depends_on:
      - postgres
      - mosquitto
    environment:
      - TZ=${TZ}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/rfkill:/dev/rfkill
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus
      - /etc/localtime:/etc/localtime:ro

  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - ${CONFIG_ROOT}/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${CONFIG_ROOT}/mosquitto/data:/mosquitto/data
      - ${CONFIG_ROOT}/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TZ=${TZ}
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - ${ZIGBEE_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    network_mode: host
    restart: unless-stopped
    command: --storage-path /data --paa-root-cert-dir /data/credentials --primary-interface enp2s0.10
    volumes:
      - ${CONFIG_ROOT}/matter-server:/data
      - /run/dbus:/run/dbus:ro

  otbr:
    container_name: otbr
    image: openthread/border-router:latest
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
      - OT_RCP_DEVICE=spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800
      - OT_INFRA_IF=${OTBR_BACKBONE_IF:-enp2s0.10}
      - OT_THREAD_IF=wpan0
      - OT_REST_LISTEN_ADDR=0.0.0.0
      - OT_REST_LISTEN_PORT=8087
      - OT_WEB_LISTEN_PORT=8086
      - OT_LOG_LEVEL=7
    volumes:
      - ${CONFIG_ROOT}/otbr:/data
      - /run/dbus:/run/dbus
    devices:
      - ${THREAD_DEVICE:-/dev/ttyUSB0}:/dev/ttyUSB0
      - /dev/net/tun:/dev/net/tun
