http:
  routers:
    hass:
      rule: "Host(`hass.iammikhail.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: hass-svc

    bambuddy:
      rule: "Host(`bambuddy.iammikhail.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: bambuddy-svc

    nas:
      rule: "Host(`nas.iammikhail.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: nas-svc

  services:
    hass-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8123"

    bambuddy-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"

    nas-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.10.201:5000"

  serversTransports:
    unifi-transport:
      insecureSkipVerify: true
